image:
  repository: ghcr.io/go-shiori/shiori
  pullPolicy: IfNotPresent
  tag: v1.5.3@sha256:18dd8f354d6f23919c55ed7e63b85747659dad81173766146e81dd051b71c0df

securityContext:
  allowPrivilegeEscalation: true
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

controller:
  replicas: 1

env:
  SHIORI_DIR: "/data"

service:
  main:
    ports:
      main:
        port: 10098
        targetPort: 8080

persistence:
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: true

postgresql:
  enabled: false
  existingSecret: "dbcreds"
  postgresqlUsername: shiori
  postgresqlDatabase: shiori

portal:
  enabled: true
